/// Flutter icons Star
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Star
///      fonts:
///       - asset: fonts/Star.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class Star {
  Star._();

  static const _kFontFam = 'Star';
  static const String? _kFontPkg = null;

  static const IconData star = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
